Actions
IDR/conda-idr-py pull request #2
Opened 2020-12-17 12:40 UTC by jburel

Replace travis by GHA
see https://github.com/jburel/conda-idr-py/actions/runs/427931730

2021-01-06 10:05 UTC, manics commented on meta.yaml
> +    - python
What happens if you don't make this change?

2021-01-06 10:05 UTC, manics commented on meta.yaml
> +  # noarch: python
Shouldn't this still be `noarch: python`?

2021-01-06 10:13 UTC, jburel commented on meta.yaml
> +    - python
it does install the wrong python version

2021-01-11 11:42 UTC, manics commented on .github/workflows/condabuild.yml
> +        if: startsWith(matrix.os, 'ubuntu')
I think you need to restrict this to one Python version too.

2021-01-11 12:13 UTC, jburel commented on .github/workflows/condabuild.yml
> +        if: startsWith(matrix.os, 'ubuntu')
yep I thought I did, it might have been on another branch

2021-01-12 12:55 UTC, manics submitted a review, later dismissed

2021-01-12 12:55 UTC, manics commented
Have the secrets been setup yet?

2021-01-12 13:37 UTC, jburel commented
not yet

2021-01-14 11:07 UTC, sbesson requested changes

2021-01-14 11:07 UTC, sbesson commented on .github/workflows/condabuild.yml
> +      channel:  ome
```suggestion
      channel:  IDR
```

2021-01-14 11:07 UTC, sbesson commented on README.md
> +[![Actions Status](https://github.com/ome/conda-idr-py/workflows/Conda/badge.svg)](https://github.com/ome/conda-idr-py/actions)
```suggestion
[![Actions Status](https://github.com/IDR/conda-idr-py/workflows/Conda/badge.svg)](https://github.com/IDR/conda-idr-py/actions)
```

2021-01-14 11:16 UTC, sbesson submitted a review, later dismissed

2021-01-19 14:50 UTC, jburel commented
bumped the version of idr-py.
Secrets added to repo (using omereleases user)

2021-02-21 20:49 UTC, sbesson approved these changes, later dismissed
Proposing to release with a similar logic as the one used in https://github.com/ome/conda-bftools/pull/6#issuecomment-780450216 (organization token?)

2021-02-21 21:52 UTC, jburel commented
I have updated the secrets so the package should end up under the correct user.

2021-02-23 12:44 UTC, jburel commented
@sbesson I had to revert 0a1676f44da96f092b86a3c758f59c10d6da2725, This now builds correctly see https://github.com/jburel/conda-idr-py/actions/runs/592533496
If any more comments, I will merge and tag

2021-02-23 13:13 UTC, sbesson commented
So is the package going to be pushed to the `ome` or the `IDR` channel?

2021-02-23 13:17 UTC, jburel commented
No. This is the confusion
The env.channel is used during the build phase to specify the channel to use to load packages like ``omero-py``
The package will be pushed to ``${{ secrets.ANACONDA_USER }}``

2021-02-23 13:19 UTC, sbesson commented
Understood, so `env.channel` determines the channel(s?) required to build the package, in this case `ome` to pull `omero-py`. Am I getting the logic correctly?

2021-02-23 13:20 UTC, jburel commented
That's correct

2021-02-23 13:21 UTC, sbesson approved these changes

2021-02-23 13:26 UTC, merged

2021-02-24 08:54 UTC, sbesson commented
Now we have a working GitHub Actions conda deployment pipeline, it might be worth looking into merging this with the upstream https://github.com/IDR/idr-py repository. At least for the most simple repositories, I assume it should be feasible to have tags pushing both to PyPI and Anaconda.